version: '3'
services:
  front:
    build:
      context: ./openweathermap-angular-frontend
    container_name: front
    restart: unless-stopped
    ports:
      - "4200:4200"
  server:
    build:
      context: ./openweathermap-nestjs-backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"